//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("DOH.WDRS.TRC", ClrNamespace="DOH.WDRS.TRC")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("DOH.WDRS", ClrNamespace="DOH.WDRS")]

namespace DOH.WDRS.TRC
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrcLookupResponse", Namespace="DOH.WDRS.TRC")]
    public partial class TrcLookupResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HCC_CodingSystemField;
        
        private string HCC_KeyField;
        
        private string HCC_NameField;
        
        private string HCC_ShortNameField;
        
        private string HC_CodingSystemField;
        
        private string HC_KeyField;
        
        private string HC_NameField;
        
        private string HC_ShortNameField;
        
        private string OBXCategoryNameField;
        
        private int TRC_IDField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCC_CodingSystem
        {
            get
            {
                return this.HCC_CodingSystemField;
            }
            set
            {
                this.HCC_CodingSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCC_Key
        {
            get
            {
                return this.HCC_KeyField;
            }
            set
            {
                this.HCC_KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCC_Name
        {
            get
            {
                return this.HCC_NameField;
            }
            set
            {
                this.HCC_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCC_ShortName
        {
            get
            {
                return this.HCC_ShortNameField;
            }
            set
            {
                this.HCC_ShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HC_CodingSystem
        {
            get
            {
                return this.HC_CodingSystemField;
            }
            set
            {
                this.HC_CodingSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HC_Key
        {
            get
            {
                return this.HC_KeyField;
            }
            set
            {
                this.HC_KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HC_Name
        {
            get
            {
                return this.HC_NameField;
            }
            set
            {
                this.HC_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HC_ShortName
        {
            get
            {
                return this.HC_ShortNameField;
            }
            set
            {
                this.HC_ShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBXCategoryName
        {
            get
            {
                return this.OBXCategoryNameField;
            }
            set
            {
                this.OBXCategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TRC_ID
        {
            get
            {
                return this.TRC_IDField;
            }
            set
            {
                this.TRC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceAcknowledgement", Namespace="DOH.WDRS.TRC")]
    public partial class ServiceAcknowledgement : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorHeaderField;
        
        private string[] ErrorsField;
        
        private string MessageField;
        
        private System.DateTime ResponseDateField;
        
        private DOH.WDRS.TRC.AcknowledgementTypeEnum ResponseTypeField;
        
        private string ServiceNameField;
        
        private string SystemNameField;
        
        private string WarningHeaderField;
        
        private string[] WarningsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorHeader
        {
            get
            {
                return this.ErrorHeaderField;
            }
            set
            {
                this.ErrorHeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseDate
        {
            get
            {
                return this.ResponseDateField;
            }
            set
            {
                this.ResponseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DOH.WDRS.TRC.AcknowledgementTypeEnum ResponseType
        {
            get
            {
                return this.ResponseTypeField;
            }
            set
            {
                this.ResponseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName
        {
            get
            {
                return this.SystemNameField;
            }
            set
            {
                this.SystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningHeader
        {
            get
            {
                return this.WarningHeaderField;
            }
            set
            {
                this.WarningHeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgementTypeEnum", Namespace="DOH.WDRS.TRC")]
    public enum AcknowledgementTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCodeLookupResponse", Namespace="DOH.WDRS.TRC")]
    public partial class ProductCodeLookupResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string ProductCodeField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupByDescriptionResponse", Namespace="DOH.WDRS.TRC")]
    public partial class LookupByDescriptionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string CodingSystemField;
        
        private string DescriptionField;
        
        private string KeyField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodingSystem
        {
            get
            {
                return this.CodingSystemField;
            }
            set
            {
                this.CodingSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
}
namespace DOH.WDRS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthConditionCatagoryCollection", Namespace="DOH.WDRS")]
    public partial class HealthConditionCatagoryCollection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DOH.WDRS.HealthConditionCatagory[] HealthConditionCatagoriesField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DOH.WDRS.HealthConditionCatagory[] HealthConditionCatagories
        {
            get
            {
                return this.HealthConditionCatagoriesField;
            }
            set
            {
                this.HealthConditionCatagoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthConditionCatagory", Namespace="DOH.WDRS")]
    public partial class HealthConditionCatagory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string CodingSystemField;
        
        private DOH.WDRS.HealthCondition[] HealthConditionsField;
        
        private string KeyField;
        
        private string NameField;
        
        private string ShortNameField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodingSystem
        {
            get
            {
                return this.CodingSystemField;
            }
            set
            {
                this.CodingSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DOH.WDRS.HealthCondition[] HealthConditions
        {
            get
            {
                return this.HealthConditionsField;
            }
            set
            {
                this.HealthConditionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthCondition", Namespace="DOH.WDRS")]
    public partial class HealthCondition : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string CodingSystemField;
        
        private string HCCKeyField;
        
        private string KeyField;
        
        private string NameField;
        
        private bool NotifyImmediateField;
        
        private string ShortNameField;
        
        private bool VisibleField;
        
        private DOH.WDRS.TRC.ServiceAcknowledgement AcknowledgementField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodingSystem
        {
            get
            {
                return this.CodingSystemField;
            }
            set
            {
                this.CodingSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCCKey
        {
            get
            {
                return this.HCCKeyField;
            }
            set
            {
                this.HCCKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotifyImmediate
        {
            get
            {
                return this.NotifyImmediateField;
            }
            set
            {
                this.NotifyImmediateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public DOH.WDRS.TRC.ServiceAcknowledgement Acknowledgement
        {
            get
            {
                return this.AcknowledgementField;
            }
            set
            {
                this.AcknowledgementField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="DOH.WDRS.TRC", ConfigurationName="ITRC")]
public interface ITRC
{
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupTRC", ReplyAction="DOH.WDRS.TRC/ITRC/LookupTRCResponse")]
    DOH.WDRS.TRC.TrcLookupResponse LookupTRC(string TestCodingSystem, string TestCode, string ResultCodingSystem, string ResultCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupTRC", ReplyAction="DOH.WDRS.TRC/ITRC/LookupTRCResponse")]
    System.Threading.Tasks.Task<DOH.WDRS.TRC.TrcLookupResponse> LookupTRCAsync(string TestCodingSystem, string TestCode, string ResultCodingSystem, string ResultCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupProductCode", ReplyAction="DOH.WDRS.TRC/ITRC/LookupProductCodeResponse")]
    DOH.WDRS.TRC.ProductCodeLookupResponse LookupProductCode(string HCKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupProductCode", ReplyAction="DOH.WDRS.TRC/ITRC/LookupProductCodeResponse")]
    System.Threading.Tasks.Task<DOH.WDRS.TRC.ProductCodeLookupResponse> LookupProductCodeAsync(string HCKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupTestByDescription", ReplyAction="DOH.WDRS.TRC/ITRC/LookupTestByDescriptionResponse")]
    DOH.WDRS.TRC.LookupByDescriptionResponse LookupTestByDescription(string Description);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupTestByDescription", ReplyAction="DOH.WDRS.TRC/ITRC/LookupTestByDescriptionResponse")]
    System.Threading.Tasks.Task<DOH.WDRS.TRC.LookupByDescriptionResponse> LookupTestByDescriptionAsync(string Description);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupResultByDescription", ReplyAction="DOH.WDRS.TRC/ITRC/LookupResultByDescriptionResponse")]
    DOH.WDRS.TRC.LookupByDescriptionResponse LookupResultByDescription(string Description);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/LookupResultByDescription", ReplyAction="DOH.WDRS.TRC/ITRC/LookupResultByDescriptionResponse")]
    System.Threading.Tasks.Task<DOH.WDRS.TRC.LookupByDescriptionResponse> LookupResultByDescriptionAsync(string Description);
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/GetHealthConditionCatagories", ReplyAction="DOH.WDRS.TRC/ITRC/GetHealthConditionCatagoriesResponse")]
    DOH.WDRS.HealthConditionCatagoryCollection GetHealthConditionCatagories();
    
    [System.ServiceModel.OperationContractAttribute(Action="DOH.WDRS.TRC/ITRC/GetHealthConditionCatagories", ReplyAction="DOH.WDRS.TRC/ITRC/GetHealthConditionCatagoriesResponse")]
    System.Threading.Tasks.Task<DOH.WDRS.HealthConditionCatagoryCollection> GetHealthConditionCatagoriesAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITRCChannel : ITRC, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TRCClient : System.ServiceModel.ClientBase<ITRC>, ITRC
{
    
    public TRCClient()
    {
    }
    
    public TRCClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TRCClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TRCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TRCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DOH.WDRS.TRC.TrcLookupResponse LookupTRC(string TestCodingSystem, string TestCode, string ResultCodingSystem, string ResultCode)
    {
        return base.Channel.LookupTRC(TestCodingSystem, TestCode, ResultCodingSystem, ResultCode);
    }
    
    public System.Threading.Tasks.Task<DOH.WDRS.TRC.TrcLookupResponse> LookupTRCAsync(string TestCodingSystem, string TestCode, string ResultCodingSystem, string ResultCode)
    {
        return base.Channel.LookupTRCAsync(TestCodingSystem, TestCode, ResultCodingSystem, ResultCode);
    }
    
    public DOH.WDRS.TRC.ProductCodeLookupResponse LookupProductCode(string HCKey)
    {
        return base.Channel.LookupProductCode(HCKey);
    }
    
    public System.Threading.Tasks.Task<DOH.WDRS.TRC.ProductCodeLookupResponse> LookupProductCodeAsync(string HCKey)
    {
        return base.Channel.LookupProductCodeAsync(HCKey);
    }
    
    public DOH.WDRS.TRC.LookupByDescriptionResponse LookupTestByDescription(string Description)
    {
        return base.Channel.LookupTestByDescription(Description);
    }
    
    public System.Threading.Tasks.Task<DOH.WDRS.TRC.LookupByDescriptionResponse> LookupTestByDescriptionAsync(string Description)
    {
        return base.Channel.LookupTestByDescriptionAsync(Description);
    }
    
    public DOH.WDRS.TRC.LookupByDescriptionResponse LookupResultByDescription(string Description)
    {
        return base.Channel.LookupResultByDescription(Description);
    }
    
    public System.Threading.Tasks.Task<DOH.WDRS.TRC.LookupByDescriptionResponse> LookupResultByDescriptionAsync(string Description)
    {
        return base.Channel.LookupResultByDescriptionAsync(Description);
    }
    
    public DOH.WDRS.HealthConditionCatagoryCollection GetHealthConditionCatagories()
    {
        return base.Channel.GetHealthConditionCatagories();
    }
    
    public System.Threading.Tasks.Task<DOH.WDRS.HealthConditionCatagoryCollection> GetHealthConditionCatagoriesAsync()
    {
        return base.Channel.GetHealthConditionCatagoriesAsync();
    }
}
